### ISSUE TITLE
change takes effect only after restart

### ISSUE THREAD

**Issue by FranklinYu** [Ragnoroct/linkme#7]
Hi, the change seems to take effect only after restart. Is this expected? If so please mention it in ReadMe. Before I notice it, I thought that my installation was broken.

By the way, awesome extension! Thanks for the effort.

**Comment by Ragnoroct** [comment]
Thank you!

Any changes to the configuration should take effect right away without a restart. I can investigate if it's not working anymore though.

**Comment by Ragnoroct** [comment]
Fixed for version 0.3.0

**Comment by FranklinYu** [comment]
The fix worked on my machine. Thanks!

**Comment by Ragnoroct** [comment]
No problem
